version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ascan-challenge-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xtdcdq0t3odp"
s3_prefix = "ascan-challenge-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
